// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_bildungsplan from "./routes/api/bildungsplan.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_debug from "./routes/api/debug.ts";
import * as $api_imagegen from "./routes/api/imagegen.ts";
import * as $api_papers from "./routes/api/papers.ts";
import * as $api_stt from "./routes/api/stt.ts";
import * as $api_tts from "./routes/api/tts.ts";
import * as $api_wikipedia from "./routes/api/wikipedia.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatAgreement from "./islands/ChatAgreement.tsx";
import * as $ChatAgreementOrIsland from "./islands/ChatAgreementOrIsland.tsx";
import * as $ChatIsland from "./islands/ChatIsland.tsx";
import * as $ChatIsland_components_ChatHeader from "./islands/ChatIsland/components/ChatHeader.tsx";
import * as $ChatIsland_hooks_useAudioPlayback from "./islands/ChatIsland/hooks/useAudioPlayback.ts";
import * as $ChatIsland_hooks_useChatPersistence from "./islands/ChatIsland/hooks/useChatPersistence.ts";
import * as $ChatIsland_hooks_useChatState from "./islands/ChatIsland/hooks/useChatState.ts";
import * as $ChatIsland_index from "./islands/ChatIsland/index.ts";
import * as $ChatIsland_services_apiService from "./islands/ChatIsland/services/apiService.ts";
import * as $ChatIsland_services_imageStore from "./islands/ChatIsland/services/imageStore.ts";
import * as $ChatIsland_services_streamService from "./islands/ChatIsland/services/streamService.ts";
import * as $ChatIsland_types from "./islands/ChatIsland/types.ts";
import * as $ChatIsland_utils_textProcessing from "./islands/ChatIsland/utils/textProcessing.ts";
import * as $ChatIsland_utils_triggerParsing from "./islands/ChatIsland/utils/triggerParsing.ts";
import * as $Header from "./islands/Header.tsx";
import * as $Menu from "./islands/Menu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/bildungsplan.ts": $api_bildungsplan,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/debug.ts": $api_debug,
    "./routes/api/imagegen.ts": $api_imagegen,
    "./routes/api/papers.ts": $api_papers,
    "./routes/api/stt.ts": $api_stt,
    "./routes/api/tts.ts": $api_tts,
    "./routes/api/wikipedia.ts": $api_wikipedia,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatAgreement.tsx": $ChatAgreement,
    "./islands/ChatAgreementOrIsland.tsx": $ChatAgreementOrIsland,
    "./islands/ChatIsland.tsx": $ChatIsland,
    "./islands/ChatIsland/components/ChatHeader.tsx":
      $ChatIsland_components_ChatHeader,
    "./islands/ChatIsland/hooks/useAudioPlayback.ts":
      $ChatIsland_hooks_useAudioPlayback,
    "./islands/ChatIsland/hooks/useChatPersistence.ts":
      $ChatIsland_hooks_useChatPersistence,
    "./islands/ChatIsland/hooks/useChatState.ts":
      $ChatIsland_hooks_useChatState,
    "./islands/ChatIsland/index.ts": $ChatIsland_index,
    "./islands/ChatIsland/services/apiService.ts":
      $ChatIsland_services_apiService,
    "./islands/ChatIsland/services/imageStore.ts":
      $ChatIsland_services_imageStore,
    "./islands/ChatIsland/services/streamService.ts":
      $ChatIsland_services_streamService,
    "./islands/ChatIsland/types.ts": $ChatIsland_types,
    "./islands/ChatIsland/utils/textProcessing.ts":
      $ChatIsland_utils_textProcessing,
    "./islands/ChatIsland/utils/triggerParsing.ts":
      $ChatIsland_utils_triggerParsing,
    "./islands/Header.tsx": $Header,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
